export const linesEgyptVape = [
  { name: 'mirage' },
  { name: 'horny hamster' },
  { name: 'club juice' },
  { name: 'vape station' },
  { name: 'fox' },
  { name: 'frisky' },
  { name: 'prestige' },
  { name: 'mangoz' },
  { name: 'eagle' },
  { name: 'arabeque' },
  { name: 'iris' },
  { name: 'gems' },
  { name: 'splash' },
  { name: 'flavor bomb' },
  { name: 'sucker punch' },
  { name: 'dollar' },
  { name: 'diy by bahz' },
  { name: 'chubby' },
  { name: 'red' },
  { name: 'alexander' },
  { name: 'my cloud' },
  { name: 'aurora' },
  { name: 'sprinkles' },
]
export const linesPremiumVape = [
  { name: 'tokyo' },
  { name: 'ripe vapes' },
  { name: 'vgod' },
  { name: 'jam monster' },
  { name: 'five pawns' },
  { name: 'Dr. Vapes'},
  { name: 'No Hype' },
  { name: 'Sad Boy' },
]

export const sizeForFilterLiquid = [
  { size: '15' },
  { size: '30' },
  { size: '60' },
  { size: '100' },
  { size: '120' },
]

export const nicotineLevelFilterLiquid = [
  { label: '0' },
  { label: '2.5' },
  { label: '3' },
  { label: '4' },
  { label: '4.5' },
  { label: '6' },
  { label: '7' },
  { label: '9' },
  { label: '12' },
  { label: '15' },
  { label: '16' },
  { label: '18' },
  { label: '24' },
  { label: '20' },
  { label: '25' },
  { label: '28' },
  { label: '30' },
  { label: '35' },
  { label: '40' },
  { label: '48' },
  { label: '50' },
]
