export const linesEgyptVape = [
  { name: 'mirage' },
  { name: 'horny hamster' },
  { name: 'club juice' },
  { name: 'vape station' },
  { name: 'fox' },
  { name: 'frisky' },
  { name: 'prestige' },
  { name: 'mangoz' },
  { name: 'eagle' },
  { name: 'arabeque' },
  { name: 'iris' },
  { name: 'gems' },
  { name: 'splash' },
  { name: 'flavor bomb' },
  { name: 'sucker punch' },
  { name: 'dollar' },
  { name: 'diy by bahz' },
  { name: 'chubby' },
  { name: 'red' },
  { name: 'alexander' },
  { name: 'my cloud' },
  { name: 'aurora' },
  { name: 'sprinkles' },
]